DROP TABLE IF EXISTS film;

CREATE TABLE film (
    film_id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    director VARCHAR(100) NOT NULL,
    release_year INTEGER CHECK (release_year > 1900),
    genre VARCHAR(50),
    rental_rate NUMERIC(5,2) CHECK (rental_rate >= 0),
    duration INTEGER CHECK (duration > 0)
);

INSERT INTO film (title, director, release_year, genre, rental_rate, duration)
VALUES
('Inception', 'Christopher Nolan', 2010, 'Sci-Fi', 4.99, 148),
('Titanic', 'James Cameron', 1997, 'Romance', 3.99, 195),
('The Dark Knight', 'Christopher Nolan', 2008, 'Action', 5.50, 152),
('Interstellar', 'Christopher Nolan', 2014, 'Sci-Fi', 6.00, 169),
('Avengers: Endgame', 'Anthony Russo', 2019, 'Action', 7.25, 181),
('The Godfather', 'Francis Ford Coppola', 1972, 'Crime', 4.50, 175),
('Forrest Gump', 'Robert Zemeckis', 1994, 'Drama', 3.75, 142),
('Joker', 'Todd Phillips', 2019, 'Drama', 5.25, 122);

-- CURSOR->POINTER: FETCHES ROWS ONE BY ONE


-- SIMPLE CURSOR:
DO $$ 
DECLARE 
REC RECORD;
CUR CURSOR FOR SELECT * FROM FILM;	-- DECLARING A CURSOR 'CUR'/ UNBOUNDED CURSOR
BEGIN
	OPEN CUR;		-- OPENING THE CURSOR

	LOOP
		FETCH CUR INTO REC; 	-- FETCH DATA USING CUR

		EXIT WHEN NOT FOUND;	-- CHECKING IF ALL ROWS ARE FETCHED

		RAISE NOTICE 'TITLE: %',REC.TITLE;

	END LOOP;

	CLOSE CUR;					-- CLOSING THE CURSOR
END $$;


-- PARAMETERISED CURSOR:
DO $$
DECLARE 
CUR CURSOR (YR INTEGER) FOR 
SELECT *FROM FILM WHERE RELEASE_YEAR=YR; -- BOUNDED CURSOR
REC RECORD;
BEGIN
		OPEN CUR(1972);

		LOOP 
			FETCH CUR INTO REC;

			EXIT WHEN NOT FOUND;
	
			RAISE NOTICE 'TITLE: %',REC.TITLE;

		END LOOP;

		CLOSE CUR;
END $$;


DO $$
DECLARE 
CUR CURSOR FOR SELECT *FROM FILM;
REC RECORD;
BEGIN 
	OPEN CUR;
	
	FETCH FIRST FROM CUR INTO REC;	-- FETCHES FIRST ROW
	RAISE NOTICE 'TITLE: %',REC.TITLE;

	FETCH LAST FROM CUR INTO REC;	-- FETCHES LAST ROW
	RAISE NOTICE 'TITLE: %', REC.TITLE;

	FETCH PRIOR FROM CUR INTO REC;	-- FETCHES THE ROW JUST ABOVE THE PRIVIOUS ROW FETCHED
	RAISE NOTICE 'TITLE: %',REC.TITLE;

	FETCH ABSOLUTE 3 FROM CUR INTO REC;	-- FETCHES ROW #03
	RAISE NOTICE 'TITLE: %',REC.TITLE;

	FETCH RELATIVE 1 FROM CUR INTO REC; -- FETCHES ONE ROW AHEAD OF THE CURRENT POSITION
	RAISE NOTICE 'TITLE: %',REC.TITLE;

	UPDATE FILM SET RELEASE_YEAR=1960
	WHERE CURRENT OF CUR;			-- UPDATING RECORD USING CURSOR
	
	CLOSE CUR;
END $$;

SELECT *FROM FILM WHERE RELEASE_YEAR=1960;


-- FUNCTION DEFINITION:
CREATE OR REPLACE FUNCTION FILM_COUNT(LEN_FROM INTEGER,LEN_TO INTEGER)
RETURNS INTEGER
LANGUAGE PLPGSQL
AS $$
DECLARE
TOTAL INTEGER := 0;
BEGIN
	SELECT COUNT(*) INTO TOTAL 
	FROM FILM WHERE DURATION BETWEEN LEN_FROM AND LEN_TO;

	RETURN TOTAL;
END $$;

SELECT FILM_COUNT(LEN_FROM:=90,LEN_TO:=190);
SELECT FILM_COUNT(90,190);
SELECT FILM_COUNT(90,LEN_TO:=190);



-- PROCEDURES:
CREATE OR REPLACE PROCEDURE add_film(
    f_title VARCHAR(100),
    f_director VARCHAR(100),
    f_release_year INTEGER,
    f_genre VARCHAR(50),
    f_rental_rate NUMERIC(5,2),
    f_duration INTEGER
)
LANGUAGE plpgsql
AS $$
BEGIN 

    INSERT INTO film(
        title,
        director,
        release_year,
        genre,
        rental_rate,
        duration
    )
    VALUES (
        f_title,
        f_director,
        f_release_year,
        f_genre,
        f_rental_rate,
        f_duration
    );

END $$;

DROP PROCEDURE add_film(
    VARCHAR,
    VARCHAR,
    INTEGER,
    VARCHAR,
    NUMERIC,
    INTEGER
);

-- CALLING A PROCEDURE:
CALL ADD_FILM('HOP', 'HALAR AHMED', 2006, 'Sci-Fi', 4.99, 108);


SELECT *FROM FILM;



drop table if exists accounts; 
create table accounts ( 
id int generated by default as identity, 
name varchar(100) not null, 
balance dec(15,2) not null, 
primary key(id) 
); 
insert into accounts(name,balance) 
values('Bob',10000); 
insert into accounts(name,balance) 
values('Alice',10000);

CREATE OR REPLACE PROCEDURE ADD_AMOUNT(
SENDER INT,
RECIEVER INT,
AMOUNT DECIMAL(10,4)
)
LANGUAGE PLPGSQL
AS $$
BEGIN
	UPDATE ACCOUNTS SET BALANCE=BALANCE-AMOUNT 
	WHERE ID=SENDER;
	
	UPDATE ACCOUNTS SET BALANCE=BALANCE+AMOUNT
	WHERE ID=RECIEVER;

	COMMIT;
END $$;

CALL ADD_AMOUNT(1,2,15);

SELECT *FROM ACCOUNTS;




