DROP TABLE IF EXISTS staff;

CREATE TABLE staff (
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(50),
    username VARCHAR(50)
);

-- 1. DATA VALIDATION BEFORE INSERTION:
CREATE OR REPLACE FUNCTION CHECK_USERNAME()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $$
BEGIN
	IF NEW.USERNAME IS NULL OR LENGTH(NEW.USERNAME)<8 THEN -- 'NEW' HERE MEANS THE VALUE THAT USER HAS GIVEN
		RAISE EXCEPTION 'USERNAME MUST BE ATLEAST 8 CHARS LONG';
	END IF;

	RETURN NEW;
END $$;

-- BINDING TRIGGER:
CREATE TRIGGER USERNAME_CHECK
BEFORE INSERT	-- CHECK BEFORE INSERTING
ON STAFF
FOR EACH ROW 
EXECUTE PROCEDURE CHECK_USERNAME();



INSERT INTO staff(name, username)
VALUES ('Ali', 'abc');  -- ❌ will fail




-- 2. SAVE THE OLD VALUES WHEN DATA CHANGES:
DROP TABLE IF EXISTS employees;

CREATE TABLE employees (
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    salary NUMERIC NOT NULL,
    PRIMARY KEY(id)
);

DROP TABLE IF EXISTS employee_audit;

CREATE TABLE employee_audit (
    id SERIAL,
    employee_id INT,
    old_salary NUMERIC,
    changed_on TIMESTAMP
);

CREATE OR REPLACE FUNCTION LOG_SALARY_UPDATE()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $$
BEGIN
	IF NEW.SALARY<>OLD.SALARY THEN
		INSERT INTO EMPLOYEE_AUDIT(EMPLOYEE_ID,OLD_SALARY,CHANGED_ON) 
		VALUES(OLD.ID,OLD.SALARY,NOW());
	END IF;

	RETURN NEW;
END $$;

-- BINDING THE TRIGGER:
CREATE TRIGGER SALARY_UPDATE_LOG
AFTER UPDATE 
ON EMPLOYEES
FOR EACH ROW
EXECUTE PROCEDURE LOG_SALARY_UPDATE();

UPDATE employees
SET salary = 80000
WHERE id = 1;



-- 3. SAVING DELETED RECORDS:
DROP TABLE IF EXISTS deleted_employees;

CREATE TABLE deleted_employees (
    id INT,
    name VARCHAR(50),
    salary NUMERIC,
    deleted_at TIMESTAMP
);

CREATE OR REPLACE FUNCTION BACKUP_DELETED_EMPLOYEES()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $$
BEGIN
	INSERT INTO deleted_employees(ID,NAME,SALARY,DELETED_AT) 
	VALUES (OLD.ID,OLD.NAME,OLD.SALARY,NOW());

	RETURN OLD;
END $$;


-- BINDING THE TRIGGER:
CREATE TRIGGER EMP_DEL_BACKUP
AFTER DELETE 
ON EMPLOYEES
FOR EACH ROW
EXECUTE PROCEDURE BACKUP_DELETED_EMPLOYEES();

DELETE FROM employees
WHERE id = 1;



-- VIEWS: USED FOR REUSING COMPLEX QUERIES:
DROP TABLE IF EXISTS STUDENTS;
CREATE TABLE students (
    id INT,
    name VARCHAR(50),
    marks INT
);
INSERT INTO students VALUES
(1, 'Ali', 85),(2, 'Sara', 60),(3, 'Ahmed', 40);


-- CREATING VIEW:
CREATE VIEW PASSED_STUDENTS AS 
SELECT ID, NAME, MARKS FROM STUDENTS
WHERE MARKS>50;

SELECT *FROM PASSED_STUDENTS;

ALTER VIEW PASSED_STUDENTS RENAME TO GOOD_STUDENTS; -- RENAMING THE VIEW


DROP TABLE IF EXISTS city;

CREATE TABLE city (
    city_id SERIAL PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    country_id INTEGER NOT NULL,
    last_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO city (city, country_id)
VALUES ('New York', 103),('Los Angeles', 103),('Chicago', 103),('Toronto', 102),('London', 101);


CREATE VIEW usa_cities AS
SELECT city, country_id
FROM city
WHERE country_id = 103;

INSERT INTO usa_cities (city, country_id)
VALUES ('San Jose', 103);	-- INSERTION USING VIEWS

DELETE FROM USA_CITIES WHERE CITY='SAN JOSE';

SELECT *FROM CITY;



-- INDEXES:
DROP TABLE IF EXISTS address;

CREATE TABLE address (
    address_id SERIAL PRIMARY KEY,
    street VARCHAR(100),
    city VARCHAR(50),
    phone VARCHAR(20)
);

INSERT INTO address (street, city, phone) VALUES
('Street 1', 'Lahore', '223664661973'),
('Street 2', 'Karachi', '111222333444'),
('Street 3', 'Islamabad', '555666777888'),
('Street 4', 'Peshawar', '999888777666'),
('Street 5', 'Quetta', '123456789000'),
('Street 6', 'Lahore', '223664661974'),
('Street 7', 'Multan', '223664661975');
-- CREATING AN INDEX: (ON PHONE NUMBERS)
CREATE INDEX ADDRESS_PHONE_IDX ON ADDRESS(PHONE);
EXPLAIN SELECT *FROM ADDRESS WHERE PHONE='223664661973';

CREATE UNIQUE INDEX IDX_PHONE_EXT
ON ADDRESS(PHONE);

SELECT STREET, PHONE FROM IDX_PHONE_EXT WHERE PHONE='223664661973';
















